export const channel = {
  store: {
    getSettings: "settings:get",
    setSettings: "settings:set",
    clearSettings: "settings:clear",
    get: "store:get",
    set: "store:set",
    clear: "store:clear",
  },
  dialog: {
    selectDirectory: "dialog:select-directory",
    showFileInFolder: "dialog:show-file-in-folder",
    selectFile: "dialog:select-file",
    openDirectory: "dialog:open-directory",
    openExternal: "dialog:open-external",
  },
  font: {
    getFonts: "font:get-fonts",
  },
  file: {
    getSize: "file:get-size",
  },
  download: {
    getList: "download:get-list",
    getDownloadData: "download:get-download-data",
    add: "download:add",
    addList: "download:add-list",
    pause: "download:pause",
    resume: "download:resume",
    cancel: "download:cancel",
    retry: "download:retry",
    sync: "download:sync",
    clear: "download:clear",
  },
  router: {
    navigate: "router:navigate",
  },
  http: {
    get: "http:get",
    post: "http:post",
  },
  player: {
    state: "player:state",
    prev: "player:prev",
    next: "player:next",
    toggle: "player:toggle",
  },
  shortcut: {
    triggered: "shortcut:triggered",
    register: "shortcut:register",
    unregister: "shortcut:unregister",
    registerAll: "shortcut:register-all",
    unregisterAll: "shortcut:unregister-all",
  },
  app: {
    getVersion: "app:get-version",
    checkUpdate: "app:check-update",
    onUpdateAvailable: "app:on-update-available",
    downloadUpdate: "app:download-update",
    updateMessage: "app:update-message",
    quitAndInstall: "app:quit-and-install",
    openInstallerDirectory: "app:open-installer-directory",
    onBeforeQuit: "app:on-before-quit",
  },
  cookie: {
    get: "cookie:get",
    set: "cookie:set",
  },
  window: {
    toggleMini: "window:toggle-mini",
    openLyricsOverlay: "window:open-lyrics-overlay",
    closeLyricsOverlay: "window:close-lyrics-overlay",
    isLyricsOverlayOpen: "window:is-lyrics-overlay-open",
    getLyricsOverlayBounds: "window:get-lyrics-overlay-bounds",
    setLyricsOverlayBounds: "window:set-lyrics-overlay-bounds",
    openLyricsOverlaySettings: "window:open-lyrics-overlay-settings",
    closeLyricsOverlaySettings: "window:close-lyrics-overlay-settings",
    isLyricsOverlaySettingsOpen: "window:is-lyrics-overlay-settings-open",
    lyricsOverlaySettingsShow: "window:lyrics-overlay-settings-show",
    minimize: "window:minimize",
    toggleMaximize: "window:toggle-maximize",
    close: "window:close",
    maximize: "window:maximize",
    unmaximize: "window:unmaximize",
    isMaximized: "window:is-maximized",
    enterFullScreen: "window:enter-full-screen",
    leaveFullScreen: "window:leave-full-screen",
    isFullScreen: "window:is-full-screen",
  },
  lyrics: {
    search: "lyrics:search",
    searchNetease: "lyrics:search-netease",
    resolveTitle: "lyrics:resolve-title",
    resolveTitleArk: "lyrics:resolve-title-ark",
  },
};
