export const defaultAppSettings: AppSettings = {
  autoStart: false,
  closeWindowOption: "hide",
  fontFamily: "system-ui",
  borderRadius: 8,
  downloadPath: "",
  primaryColor: "#5a9e7c",
  backgroundColor: "",
  audioQuality: "auto",
  hiddenMenuKeys: [],
  displayMode: "list",
  ffmpegPath: "",
  themeMode: "system",
  pageTransition: "none",
  showSearchHistory: true,
  proxySettings: {
    type: "none",
    host: "",
    port: undefined,
    username: "",
    password: "",
  },
  sideMenuCollapsed: false,
  sideMenuWidth: 184,
  sideMenuCollectionFolded: {
    created: false,
    collected: false,
  },
  reportPlayHistory: true,
  localMusicDirs: [],
  showLyricsTranslation: true,
  showLyricsFurigana: false,
  playbarCollapsed: false,
};
